# Generated by Django 5.2.3 on 2025-06-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(default='summary', max_length=50),
            preserve_default=False,
        ),
    ]
