# Generated by Django 5.2.3 on 2025-06-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_article_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
