# Generated by Django 5.2.3 on 2025-07-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_alter_article_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='video',
        ),
    ]
