# Generated by Django 5.2.3 on 2025-07-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_remove_article_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
