# Generated by Django 5.2.3 on 2025-07-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_article_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='posttype',
            field=models.CharField(choices=[('standard', 'Standard'), ('video', 'Video'), ('audio', 'Audio')], default='standard', max_length=10),
        ),
    ]
