"""
Django settings for blogwithdjango project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []








# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blogApp',
    #'tinymce',
    #'prose',
    #'django_summernote',
    'ckeditor',
    'ckeditor_uploader',

]

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_Full': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'forms', 'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea',
                                        'Select', 'Button', 'ImageButton', 'HiddenField']},
            '/',
            {'name': 'basicstyles', 'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript',
                                              'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph', 'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent',
                                            '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft',
                                            'JustifyCenter', 'JustifyRight', 'JustifyBlock',
                                            '-', 'BidiLtr', 'BidiRtl', 'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert', 'items': [
                'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley',
                'SpecialChar', 'PageBreak', 'Iframe', 'Embed', 'EmbedSemantic'
            ]},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'about', 'items': ['About']},
            {'name': 'custom', 'items': ['Preview', 'Print', 'CodeSnippet']}
        ],
        'extraPlugins': ','.join([
            'uploadimage',  # يجب أن تكون أولاً
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',
            'codesnippet',
        ]),
        'removePlugins': 'stylesheetparser',
        'height': 600,
        'width': 'auto',
        'toolbar': 'Full',
        'codeSnippet_theme': 'monokai_sublime',
        'allowedContent': True,
        'autoParagraph': False,
    }
}



TINYMCE_DEFAULT_CONFIG = {
    "height": 700,
    "width": "100%",
    "menubar": True,
    "plugins": (
        "advlist anchor autolink charmap code fullscreen help image insertdatetime "
        "link lists media preview searchreplace table visualblocks wordcount"
    ),
    "toolbar": (
        "undo redo | styleselect | bold italic underline strikethrough | "
        "forecolor backcolor | alignleft aligncenter alignright alignjustify | "
        "bullist numlist outdent indent | link image media table | "
        "code fullscreen preview | help"
    ),
    "image_advtab": True,
    "media_live_embeds": True,
    "media_alt_source": True,
    "media_dimensions": True,
    "media_poster": True,
    "table_appearance_options": True,
    "automatic_uploads": True,
    "paste_data_images": True,
    "file_picker_types": "file image media",
}

LANGUAGE_CODE = 'fr'
SUMMERNOTE_CONFIG = {
    # ✅ تحديد حجم المحرر
    'summernote': {
        'width': '100%',
        'height': '400px',
    },

    # ✅ السماح فقط بأنواع الملفات الآمنة (فيديو وصوت)
    'attachment_require_authentication': True,  # منع الرفع من الزوار
    'allowed_file_extensions': ['mp3', 'wav', 'ogg', 'aac', 'mp4', 'mkv', 'webm'],
    'default_css': (
        '//stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css',
    ),

    # ✅ تقييد التحميل للمستخدمين الموثوقين فقط (مثلاً المسجلين)
    'attachment_upload_to': 'media_uploads/safe/',
}
SUMMERNOTE_CONFIG = {
    'attachment_require_authentication': True,
    
}
SUMMERNOTE_CONFIG = {
    'iframe': False,  # لكي يندمج مع الستايل الخاص بموقعك
    'summernote': {
        'width': '100%',
        'height': '700px',

        'toolbar': [
            ['style', ['style']],
            ['font', ['bold', 'italic', 'underline', 'strikethrough', 'clear']],
            ['fontname', ['fontname']],
            ['fontsize', ['fontsize']],
            ['color', ['color']],
            ['para', ['ul', 'ol', 'paragraph']],
            ['height', ['height']],
            ['table', ['table']],
            ['insert', ['link', 'picture', 'video', 'hr']],
            ['view', ['fullscreen', 'codeview', 'help']],
            ['misc', ['undo', 'redo']]
        ],

        'styleTags': [
            'p', 'blockquote', 'pre', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'
        ],

        'fontNames': [
            'Arial', 'Arial Black', 'Comic Sans MS', 'Courier New',
            'Helvetica', 'Impact', 'Tahoma', 'Times New Roman', 'Verdana',
            'Amiri', 'Cairo', 'Lateef', 'Droid Arabic Kufi'
        ],
        'fontSizes': ['8', '9', '10', '11', '12', '14', '16', '18', '20', '22', '24', '36', '48' ,'64'],

        'lineHeights': ['0.5', '1.0', '1.2', '1.4', '1.5', '1.75', '2.0', '3.0'],

        'dialogsInBody': True,
        'disableDragAndDrop': False,
        'codeviewFilter': False,  # للسماح بكل HTML
        'codeviewIframeFilter': True,
    },

    'attachment_require_authentication': False,
    'disable_attachment': False,

    'summernote_css': (
        '//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/summernote-bs4.min.css',
    ),
    'summernote_js': (
        '//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.18/summernote-bs4.min.js',
    ),

    'default_css': (
        'https://fonts.googleapis.com/css2?family=Cairo:wght@400;700&display=swap',
    ),

    'allowed_file_extensions': [
        'jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg',
        'mp3', 'ogg', 'wav', 'flac', 'aac', 'm4a',
        'mp4', 'avi', 'mov', 'mkv', 'webm',
        'pdf', 'doc', 'docx', 'xls', 'xlsx', 'zip', 'rar'
    ],

    'lang': 'ar-AR',  # دعم اللغة العربية بالكامل
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'blogwithdjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'blogApp.context_processors.categories_processor',

            ],
        },
    },
]

WSGI_APPLICATION = 'blogwithdjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_URL = '/static/'

# هذا مجلد الملفات النهائية بعد جمعها
STATIC_ROOT = BASE_DIR / 'staticfiles'

# وهذا مجلد الملفات أثناء التطوير (قبل التجميع)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



